language: python
python:
  - "3.6.6"

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests -> dos formas: pytest, o make
script:
  - pytest #mirar documento pytest
